[project]
name = "deepseek-ocr-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "addict>=2.4.0",
    "easydict>=1.13",
    "einops>=0.8.1",
    "psutil>=7.1.1",
    "transformers==4.46.3",
    "wheel>=0.45.1",
]
